version: '3.2'
services:
  gitbook:
    image: registry.cn-shenzhen.aliyuncs.com/yuanjm/gitbook:1.0
    container_name: gitbook
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/gitbook
    restart: always